### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by maxguru** [silvio/docker-matrix#28]
I've set up an instance of this container (behind reverse proxy for port 443; direct for port 8448).  I created an account and logged in to my instance using riot-web client with electron.  It seems to be working, however, the list of public rooms is empty and I am getting the following errors in the docker logs when I try to search for a room,

```
5/21/2017 11:50:39 PM2017-05-22 06:50:39,342 - synapse.http.outbound - 239 - INFO - GET-114- {GET-O-5} [matrix.org] Result: 502 Bad Gateway
5/21/2017 11:50:39 PM2017-05-22 06:50:39,366 - root - 181 - WARNING - GET-114- Error retrieving alias
5/21/2017 11:50:39 PM2017-05-22 06:50:39,406 - synapse.http.server - 126 - ERROR - GET-114- 502: Bad Gateway
5/21/2017 11:50:39 PMTraceback (most recent call last):
5/21/2017 11:50:39 PM  File "/usr/local/lib/python2.7/dist-packages/synapse/http/server.py", line 116, in wrapped_request_handler
5/21/2017 11:50:39 PM    yield request_handler(self, request, request_metrics)
5/21/2017 11:50:39 PM  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1299, in _inlineCallbacks
5/21/2017 11:50:39 PM    result = result.throwExceptionIntoGenerator(g)
5/21/2017 11:50:39 PM  File "/usr/local/lib/python2.7/dist-packages/twisted/python/failure.py", line 393, in throwExceptionIntoGenerator
5/21/2017 11:50:39 PM    return g.throw(self.type, self.value, self.tb)
5/21/2017 11:50:39 PM  File "/usr/local/lib/python2.7/dist-packages/synapse/http/server.py", line 255, in _async_render
5/21/2017 11:50:39 PM    callback_return = yield callback(request, **kwargs)
5/21/2017 11:50:39 PM  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1299, in _inlineCallbacks
5/21/2017 11:50:39 PM    result = result.throwExceptionIntoGenerator(g)
5/21/2017 11:50:39 PM  File "/usr/local/lib/python2.7/dist-packages/twisted/python/failure.py", line 393, in throwExceptionIntoGenerator
5/21/2017 11:50:39 PM    return g.throw(self.type, self.value, self.tb)
5/21/2017 11:50:39 PM  File "/usr/local/lib/python2.7/dist-packages/synapse/rest/client/v1/directory.py", line 50, in on_GET
5/21/2017 11:50:39 PM    res = yield dir_handler.get_association(room_alias)
5/21/2017 11:50:39 PM  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1299, in _inlineCallbacks
5/21/2017 11:50:39 PM    result = result.throwExceptionIntoGenerator(g)
5/21/2017 11:50:39 PM  File "/usr/local/lib/python2.7/dist-packages/twisted/python/failure.py", line 393, in throwExceptionIntoGenerator
5/21/2017 11:50:39 PM    return g.throw(self.type, self.value, self.tb)
5/21/2017 11:50:39 PM  File "/usr/local/lib/python2.7/dist-packages/synapse/handlers/directory.py", line 178, in get_association
5/21/2017 11:50:39 PM    ignore_backoff=True,
5/21/2017 11:50:39 PM  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1299, in _inlineCallbacks
5/21/2017 11:50:39 PM    result = result.throwExceptionIntoGenerator(g)
5/21/2017 11:50:39 PM  File "/usr/local/lib/python2.7/dist-packages/twisted/python/failure.py", line 393, in throwExceptionIntoGenerator
5/21/2017 11:50:39 PM    return g.throw(self.type, self.value, self.tb)
5/21/2017 11:50:39 PM  File "/usr/local/lib/python2.7/dist-packages/synapse/federation/transport/client.py", line 188, in make_query
5/21/2017 11:50:39 PM    ignore_backoff=ignore_backoff,
5/21/2017 11:50:39 PM  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1299, in _inlineCallbacks
5/21/2017 11:50:39 PM    result = result.throwExceptionIntoGenerator(g)
5/21/2017 11:50:39 PM  File "/usr/local/lib/python2.7/dist-packages/twisted/python/failure.py", line 393, in throwExceptionIntoGenerator
5/21/2017 11:50:39 PM    return g.throw(self.type, self.value, self.tb)
5/21/2017 11:50:39 PM  File "/usr/local/lib/python2.7/dist-packages/synapse/http/matrixfederationclient.py", line 451, in get_json
5/21/2017 11:50:39 PM    ignore_backoff=ignore_backoff,
5/21/2017 11:50:39 PM  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1301, in _inlineCallbacks
5/21/2017 11:50:39 PM    result = g.send(result)
5/21/2017 11:50:39 PM  File "/usr/local/lib/python2.7/dist-packages/synapse/http/matrixfederationclient.py", line 250, in _request
5/21/2017 11:50:39 PM    response.code, response.phrase, body
5/21/2017 11:50:39 PMHttpResponseException: 502: Bad Gateway
```

Any ideas?

**Comment by silvio** [comment]
@maxguru just a small idea: setup your SRV records?

I close this, its not a docker-matrix problem.
