### ISSUE TITLE
Can't create room/contact user

### ISSUE THREAD

**Issue by ghost** [silvio/docker-matrix#78]
Hello,
I just launched a synapse server instance using your docker image.
It runs just fine, i registered two users to test it.
But when I try to contact another user, a 404 error appears in my logs. I've tried to contact other accounts, out of my instance, but none of them works.
Here is what happen in my log file:
>2019-04-16 16:07:11,179 - synapse.http.client - 295 - INFO - POST-46 - Received response to GET https://matrix.foxty.pw/_matrix/identity/api/v1/lookup?medium=email&address=tom%40matrix.foxty.pw: 404,
2019-04-16 16:07:11,181 - synapse.http.server - 112 - ERROR - POST-46 - Failed handle request via 'RoomCreateRestServlet': <SynapseRequest at 0x7f8b5700a3f8 method=u'POST' uri=u'/_matrix/client/r0/createRoom' clientproto=u'HTTP/1.1' site=8448>,
Traceback (most recent call last):,
  File "/usr/local/lib/python2.7/dist-packages/synapse/http/server.py", line 81, in wrapped_request_handler,
    yield h(self, request),
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks,
    result = result.throwExceptionIntoGenerator(g),
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator,
    return g.throw(self.type, self.value, self.tb),
  File "/usr/local/lib/python2.7/dist-packages/synapse/http/server.py", line 316, in _async_render,
    callback_return = yield callback(request, **kwargs),
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks,
    result = result.throwExceptionIntoGenerator(g),
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator,
    return g.throw(self.type, self.value, self.tb),
  File "/usr/local/lib/python2.7/dist-packages/synapse/rest/client/v1/room.py", line 74, in on_POST,
    requester, self.get_room_config(request),
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks,
    result = result.throwExceptionIntoGenerator(g),
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator,
    return g.throw(self.type, self.value, self.tb),
  File "/usr/local/lib/python2.7/dist-packages/synapse/handlers/room.py", line 629, in create_room,
    txn_id=None,,
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks,
    result = result.throwExceptionIntoGenerator(g),
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator,
    return g.throw(self.type, self.value, self.tb),
  File "/usr/local/lib/python2.7/dist-packages/synapse/handlers/room_member.py", line 697, in do_3pid_invite,
    id_server, medium, address,
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks,
    result = result.throwExceptionIntoGenerator(g),
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator,
    return g.throw(self.type, self.value, self.tb),
  File "/usr/local/lib/python2.7/dist-packages/synapse/handlers/room_member.py", line 737, in _lookup_3pid,
    "address": address,,
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks,
    result = result.throwExceptionIntoGenerator(g),
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator,
    return g.throw(self.type, self.value, self.tb),
  File "/usr/local/lib/python2.7/dist-packages/synapse/http/client.py", line 412, in get_json,
    body = yield self.get_raw(uri, args, headers=headers),
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks,
    result = g.send(result),
  File "/usr/local/lib/python2.7/dist-packages/synapse/http/client.py", line 493, in get_raw,
    raise HttpResponseException(response.code, response.phrase, body),
HttpResponseException: 404: Not Found,

Any idea ?
Thanks !

**Comment by mvgorcum** [comment]
I think this means you filled in the URL to your synapse server as the identity server when you logged in. This container doesn't supply an identity server, so if you want to self host one, you'll have to find an identity server (for example [mxisd](https://github.com/kamax-matrix/mxisd/)) or use the default matrix-hosted identity server (at vector.im).

Note that the identity server has as main purpose to give the 3pid -> mxid mapping (eg using an email address to find the matrix ID).

**Comment by ghost** [comment]
Thanks for the precision !
Closing the issue !
